name: s
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.52+52

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  go_router: ^17.0.1
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0 
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  equatable: ^2.0.7
  flutter_iconly: ^1.0.2
  flutter_local_notifications: ^20.1.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.2
  path_provider: ^2.1.6
  intl: ^0.20.2
  uuid: ^4.5.3
  fl_chart: ^1.2.0
  audioplayers: ^6.6.0
  table_calendar: ^3.2.0
  dartz: ^0.10.1
  package_info_plus: ^9.0.1
  window_manager: ^0.5.2
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  flutter_speed_dial: ^7.0.0
  file_picker: ^11.0.2
  share_plus: ^12.0.2
  just_audio: ^0.10.6
  dio: ^5.11.0
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  pretty_dio_logger: ^1.4.0
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
    - assets/images/wallpapers/
    - assets/audio/notification.mp3
    - assets/json/
    - assets/text/quran-uthmani-min.txt
    - assets/text/asmaa.txt
    - assets/text/arbaoon.txt
    - assets/text/tabeen.txt

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs.otf
    - family: Arabesque
      fonts:
        - asset: assets/fonts/AGA-Arabesque.ttf

icons_launcher:
  image_path: "assets/images/png/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true

# dart run icons_launcher:create
# flutter gen-l10n
